# Generated by Django 5.1.2 on 2024-10-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.CharField(max_length=12)),
                ('msg', models.TextField()),
            ],
            options={
                'db_table': 'Contact_Us',
            },
        ),
        migrations.CreateModel(
            name='gatepass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, unique=True)),
                ('transpoter_name', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=50)),
                ('vehical_owner_name', models.CharField(max_length=50)),
                ('vehical_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('gate_in_time', models.TimeField()),
                ('driver_number', models.CharField(max_length=10)),
                ('driver_licence_no', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Gate Pass Form',
            },
        ),
    ]
