# Generated by Django 5.1.2 on 2024-10-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamatulmsl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='form_number',
            field=models.IntegerField(default=1),
        ),
    ]
