# Generated by Django 5.1.2 on 2024-10-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamatulmsl', '0002_gatepass_form_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatepass',
            old_name='userid',
            new_name='USERID',
        ),
    ]
