# Generated by Django 5.1.2 on 2024-10-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamatulmsl', '0003_rename_userid_gatepass_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatepass',
            old_name='transpoter_name',
            new_name='transporter_name',
        ),
    ]
