# Generated by Django 5.1.2 on 2024-10-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamatulmsl', '0004_rename_transpoter_name_gatepass_transporter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatepass',
            old_name='vehical_owner_name',
            new_name='vehicle_owner_name',
        ),
    ]
