# Generated by Django 5.1.2 on 2024-11-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamatulmsl', '0007_alter_gatepass_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='id',
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='form_number',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
