# Generated by Django 5.1.4 on 2024-12-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jamatulmsl", "0009_gatepass_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gatepass",
            name="amount",
            field=models.IntegerField(default=20),
        ),
    ]
